### ISSUE TITLE
Save Failed Sub Frames will not enable after saving

### ISSUE THREAD

**Issue by Ace1530** [smart-underworld/seestar_alp#110]
When I choose enable Save Failed Sub Frames and click save it reverts back to disable, this is the only setting that does this. Seestar firmware version 2.76, Updated alp software today 8/3/2024
![seestar settings](https://github.com/user-attachments/assets/e52bc17b-d597-43b1-bdc6-c392eea3e642)

**Comment by erewhon** [comment]
This should now be fixed as of PR #112
