### ISSUE TITLE
Steering the Start-Up Sequence

### ISSUE THREAD

**Issue by jabamula** [smart-underworld/seestar_alp#127]
I am really fine with the Start-Up Sequence with my EQ position of 61 degrees, and am worried that it could be changed. Therefore I have two parallel suggestions:
- making the start-up sequence based on the latitude of the user, so it for sure receives higher altitudes that finds stars 
- having settings for the user to change the sequence logic. I don't fully understand, how the current system works as it makes four moves. If it would not do the last move, I might not get the HC as it then would head to the sky of highest blockage in my place. I presume that I could do the slew with the app or with Bruno, but it would be a complication in the workflow.

**Comment by YungKC** [comment]
Existing logic makes 4 moves because I had not discovered a now better
command to move. I will fix that.

It's also probably best to have the startup sequence to accept a parameter
for how far up it should go.

**Comment by jabamula** [comment]
Yes, a parameter is a good choice. 

Also, it would be good to have advice regarding the EQ mode about how the Seestar positioning (in what cardinal direction the Start button is heading) affects the Start-Up.
