### ISSUE TITLE
Is there a better way to show telescope level information?

### ISSUE THREAD

**Issue by erewhon** [smart-underworld/seestar_alp#155]
Right now, we just show a single number in the web interface.  The Seestar app on the other hand shows a two dimensional view.  (At least on iOS it's the same view as the Level app.)    Ideally it would be nice to have a more two dimensional representation of the level.

**Comment by mconsidine** [comment]
'get_device_settings' has a 'balance_sensor' field with x,y,z accelerometer readings and an angle calculation.  I think 'angle' is what is shown in the app.  I'll check if I've already calculated the x and y components somewhere.  Don't think I did.On Aug 22, 2024 1:43 AM, Steven Byrnes ***@***.***> wrote:
Right now, we just show a single number in the web interface.  The Seestar app on the other hand shows a two dimensional view.  (At least on iOS it's the same view as the Level app.)    Ideally it would be nice to have a more two dimensional representation of the level.

**Comment by quake101** [comment]
Do we just want to display the x,y from get_device_state?

**Comment by YungKC** [comment]
There must be a cool HTML widget for a level bubble.

**Comment by quake101** [comment]
Maybe we could adapt this: https://developer.mozilla.org/en-US/docs/Web/API/Device_orientation_events/Detecting_device_orientation

**Comment by YungKC** [comment]
That's pretty cool.
