### ISSUE TITLE
Web interface to distribute mosaic panels across multiple Seestars

### ISSUE THREAD

**Issue by erewhon** [smart-underworld/seestar_alp#162]
Since it is now possible to specify panels in a given mosaic, we could create a web interface that takes a single mosaic, and divides it up across multiple Seestars.

**Comment by YungKC** [comment]
Care is needed in entering the session time. Current logic expects it to be
the total as if all panels in the mosaic are captured in sequence.

**Comment by erewhon** [comment]
> Now that we have selected_panels option for mosaics, anyone wants to figure out how to incorporate this into SSC to automatically distribute a mosaic project across multiple Seestars?

**Comment by erewhon** [comment]
With recent federation code, this is now complete.
