### ISSUE TITLE
Add startup section in config.toml

### ISSUE THREAD

**Issue by wileecyte** [smart-underworld/seestar_alp#169]
Allow users to specify non-persistent settings that would be set at startup.

**Comment by wileecyte** [comment]
Spitballing ideas:
- Dedicated page to set the values and save to config.toml (or some other config file)
- Leverage the existing Start-Up Sequence to actually set values
- Ideas of settings to include: dither settings, exposure settings, dew heater, open arm to position

**Comment by quake101** [comment]
front/defaults.toml ?

**Comment by YungKC** [comment]
Startup defaults should not require front web GUI to execute, although the
GUI can update the values. Therefore, these startup settings should be in
device/config.toml.<*>

**Comment by quake101** [comment]
Good point!

**Comment by smart-underworld** [comment]
Implemented.
