### ISSUE TITLE
Import/export

### ISSUE THREAD

**Issue by jabamula** [smart-underworld/seestar_alp#209]
Off-line, forked and committed just the latest changes.
1.
I tried to do the following schedule:

- dew_heater
- object
- shutdown

The result was that the schedule couldn't exported and it gave the following error:
_This XML file does not appear to have any style information associated with it. The document tree is shown below.
error
     500 Internal Server Error_

2.
If I left out the shutdown:

- dew_heater
- object

It did export the schedule, but as I tried to import it back, the same error occurred.

The saved file is:
action,local_time,timer_sec,try_count,target_name,is_j2000,ra,dec,is_use_lp_filter,session_time_sec,ra_num,dec_num,panel_overlap_percent,gain,is_use_autofocus,heater,nokey
pi_output_set2,,,,,,,,,,,,,,,"{'state': True, 'value': 90}",
start_mosaic,,,,SS Cyg,True,21h42m42.8s,+43d35m9.9s,False,1600,1,1,100,80,True,,

3.
If I only put the objects, it exports and import just fine.

**Comment by jabamula** [comment]
And the similar error comes on-line.

**Comment by wileecyte** [comment]
Dew heater and lp filter scheduled items have been corrected with this commit: https://github.com/smart-underworld/seestar_alp/commit/2b11cea49cb5a43324427675ba35ca55b0dba6c5
