### ISSUE TITLE
[Enhancement] Pull name of object if available from Stellarium; Tooltip idea

### ISSUE THREAD

**Issue by mconsidine** [smart-underworld/seestar_alp#231]
Pulling the coordinates from a highlight object in Stellarium worked flawlessly using v24.1 of Stellarium.  Am wondering if the object's name is also some available to use in populating the target name field in 'Image' tab.

It could also be useful to have a tooltip reminder to users to ensue that the Remote Control plugin in Stellarium is active (the defaults worked fine for me).

mconsidine

**Comment by xscode** [comment]
I just implemented pulling the object name, just need to wait for the pull request to go through.

**Comment by YungKC** [comment]
PR merged. Please confirm and close once verified.
