### ISSUE TITLE
Docker correction ?

### ISSUE THREAD

**Issue by RastaTaz** [smart-underworld/seestar_alp#240]
Hi,

Don't know why, but I had to make below changes to files in the "./docker" folder to get a sucessfull build and run (using the run.sh as documented).

```
diff --git a/docker/Dockerfile b/docker/Dockerfile
index 9a88860..b58fed1 100644
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -31,7 +31,8 @@ RUN apt-get update && \
         software-properties-common \
         vim \
         git \
-        tzdata && \
+        tzdata \
+       libgl1-mesa-glx && \
     rm -rf /var/lib/apt/lists/* && \
     apt-get clean

diff --git a/docker/util.sh b/docker/util.sh
index 75d090e..601da0a 100644
--- a/docker/util.sh
+++ b/docker/util.sh
@@ -15,11 +15,11 @@ docker_build() {
         fi
     fi

-    if [ "${docker_build_PROGRESS}" == "true" ]; then
-        docker_build_PROGRESS="--progress plain"
-    else
+#    if [ "${docker_build_PROGRESS}" == "true" ]; then
+#        docker_build_PROGRESS="--progress plain"
+#    else
         docker_build_PROGRESS=""
-    fi
+#    fi

     read -d '' DOCKER_BUILD_COMMAND <<EOM
 docker build \
```

## Explanations:
- Regarding the Dockerfile: I had to include the  "libgl1-mesa-glx" package because of a missing lbGL.so.1 shared object
- Regarding the util.sh: my docker version 27.2.0 doesn't support the "--progress " param (the corresponding diff is a "quick'n dirty" fix... sorry !)

## Additional question:
Doesn't the config.toml.example template file in the same "./docker" folder needs updating ?
=> Indeed: it's missing the [seestar_initialization] section mentionned somewhere else (I think I got it from the binary/static tar.gz package for release deliveries from rrowley42 repo linked in the readme.md of current repo)

**Comment by lnxbil** [comment]
I think you're refering to #196, are you?

**Comment by RastaTaz** [comment]
Hi, Inxbil !
Thanks for looking at the issue.
Indeed for the additional question: I was refering to the update you mentionned.

=> The toml example config file in the docker folder does not have those updates.

The first part is more about the Dockerfile and util.sh: maybe I should have created separate issues...

**Comment by bguthro** [comment]
This was addressed as part of https://github.com/smart-underworld/seestar_alp/pull/366
