### ISSUE TITLE
Save / restore schedules

### ISSUE THREAD

**Issue by erewhon** [smart-underworld/seestar_alp#28]
Add some mechanism to save and restore schedules on the scheduler page.   

This would be useful for the following reasons:
- make minor edits to a schedule without having to add a general edit mechanism
- run the same schedule on multiple telescopes
- run the same schedule on multiple nights
- create a mosaic plan using a third-party tool (e.g. Telescopius)
- create a schedule offline

A CSV format would be the simplest.   (Telescopius, for example, dumps out mosaics as CSV.).  We can always add richer formats later.

**Comment by erewhon** [comment]
See https://github.com/smart-underworld/seestar_alp/issues/22#issuecomment-2198810292

**Comment by quake101** [comment]
Is anyone working on this? If not, I could start working on it.

**Comment by erewhon** [comment]
> Is anyone working on this? If not, I could start working on it.

I would ask @wileecyte.  Plus he's working on some offline stuff that's pretty disruptive to the core.  I think it will land soon.

**Comment by erewhon** [comment]
This should be resolved by #63
