### ISSUE TITLE
Docker fails on container startup

### ISSUE THREAD

**Issue by RastaTaz** [smart-underworld/seestar_alp#306]
Since few days now, using container version build using the documented run.sh script in the docker folder (and modifications suggested in issue #240) , startup of resulting image fails with following error at the end of run.sh script execution:

```
# ./docker/run.sh -b -t "Europe/Paris" -i
(...)
Successfully tagged seestar_alp:latest
2024-09-29T09:35:42: startup: indiserver -f /tmp/seestar
echo "start /home/seestar/seestar_alp/indi/seestar.py -n \"SeeTaz\" -c \"1\"" > /tmp/seestar
Traceback (most recent call last):
  File "/home/seestar/seestar_alp/device/app.py", line 64, in <module>
    from device import discovery
ModuleNotFoundError: No module named 'device'
Traceback (most recent call last):
  File "/home/seestar/seestar_alp/front/./app.py", line 37, in <module>
    from device.seestar_logs import SeestarLogging
ModuleNotFoundError: No module named 'device'

```

**Comment by lnxbil** [comment]
I ran into the same problem on tag v.2.1.1 and `main`. Anything I can do to debug?

**Comment by bguthro** [comment]
I've pushed a fix...but just know that none of the active developers use the docker path...so this is really a "best effort" approach.

**Comment by lnxbil** [comment]
Thank you. Yes this fixes the docker bootup errors.

**Comment by RastaTaz** [comment]
Hi bguthro,
Thanks for taking time to look at the issue.
Didn't knew about devs not using the docker version: I thought I'd use this to avoid any version/lib mismatch...
=> Will look at directly using the "python way".

Thanks again !

**Comment by RastaTaz** [comment]
Same here, but bguthro being behind many commits of the project: I'll take his sayings for granted.
Moreover, the issue has been around for too long for not being fixed earlier if that was not the case...

Also, may I  suggest the folloiing change so the INDI version would work as well:
```
diff --git a/docker/entrypointINDI.sh b/docker/entrypointINDI.sh
index 8ebb891..0dcfaef 100755
--- a/docker/entrypointINDI.sh
+++ b/docker/entrypointINDI.sh
@@ -7,5 +7,5 @@ indiserver -f /tmp/seestar &
 cd /home/seestar/seestar_alp/indi
 python3 start_indi_devices.py

-cd /home/seestar/seestar_alp/front
+cd /home/seestar/seestar_alp
 python3 ./root_app.py
```

Yes, I'm using the INDI flavour of seestar_alp through docker: maybe a rare case... but I can drive the S50 through Stellarium that way: that's much easier than putting in coordinates or names for a Simbad search (pertinent if you're in an offline situation or on the move in a remote location). Plus my other scope is also driven through Stellarium so this makes sense for me to have everything in the same software.
