### ISSUE TITLE
save_all_frames value not brought in from config.toml

### ISSUE THREAD

**Issue by mconsidine** [smart-underworld/seestar_alp#307]
Before starting seestar_alp I editted config.toml to customize settings, among which was to turn save_all_frames to true.
When I loaded SSC and checked SSC Config, this was unchecked.
Looking at the .html I see this at line 177
  {% if config.save_all_frames == true %}
But comparing to a similar setting on line 171, I believe it should be
  {% if config.init_save_all_frames == true %}

Manually making that change to the html seems to confirm this.

**Comment by smart-underworld** [comment]
I believe @bguthro should be notified.
