### ISSUE TITLE
Front end broken in Docker container

### ISSUE THREAD

**Issue by pcyvr** [smart-underworld/seestar_alp#32]
The front end no longer works when using the Docker container.  I suspect `app.py` (line 595)

`with make_server("127.0.0.1", 5432, app, handler_class=LoggingWSGIRequestHandler) as httpd: `

should be

`with make_server("0.0.0.0", 5432, app, handler_class=LoggingWSGIRequestHandler) as httpd:`

**Comment by erewhon** [comment]
@wileecyte said he'll d it.

**Comment by wileecyte** [comment]
Made the front end UI use options from config.toml.
Added a new 'uiport' to specify something other than 5432
Updated the docker/config.toml.example to add uiport.

**Comment by erewhon** [comment]
Resolved by #42
