### ISSUE TITLE
Integration time not accurate at other than 10 second frames

### ISSUE THREAD

**Issue by jeffreypkelly** [smart-underworld/seestar_alp#362]
I was running 20 second frame times last night and the integration time seemed to be updating at a 10 second rate.
Possible? :
  "integration_time": str(timedelta(seconds=stack.get("stacked_frame") * 10)),

**Comment by erewhon** [comment]
Yes, sorry. I had made a note in the code that I needed to fix it to take into account the exposure length.   Let me look at that.  (I added the field during a live stream, so it was very much on-the-fly.)
