### ISSUE TITLE
docker - image building error

### ISSUE THREAD

**Issue by elroyski** [smart-underworld/seestar_alp#364]
hello!
git clone repo, 
run build ./docker/run.sh -b -i -t "Europa/Warsaw"
I depend on the cooperation with Stellarium :)
 
`#15 149.7 Successfully installed lxml-5.3.0 pillow-11.0.0 pyindi-0.0.0 tornado-6.4.1
#15 149.7 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#15 DONE 150.6s

#16 exporting to image
#16 exporting layers
#16 exporting layers 2.7s done
#16 writing image sha256:d06f11198b35e833981747194bad30a84165798fe95417749969c407093b2e41 done
#16 naming to docker.io/library/seestar_alp:latest done
#16 DONE 2.8s
2024-10-15T17:38:04: startup: indiserver -f /tmp/seestar
echo "start /home/seestar/seestar_alp/indi/seestar.py -n \"Seestar Alpha\" -c \"1\"" > /tmp/seestar
python3: can't open file '/home/seestar/seestar_alp/front/./root_app.py': [Errno 2] No such file or directory
`

**Comment by bguthro** [comment]
Fixed by PR-365: https://github.com/smart-underworld/seestar_alp/pull/365
