### ISSUE TITLE
raspberry pi systemctl setup needs to be tweaked.

### ISSUE THREAD

**Issue by stephen-hocking** [smart-underworld/seestar_alp#388]
When starting seestar (sudo systemctl start seestar) it complains about not being able to start "indi". If you do a "sudo systemctl start INDI" and then attempt to start seestar again, it's happy. One only sees this when messing about with system services (I had had to tell it to search for an IP of "seestar", rather than "seestar.local". The raspberry pi section builds and runs well under  the Linux subsystem on an ARM chromebook, although you have to direct your web browser at the ip address of the linux subsystem , rather than localhost. Waiting for a clear night to fully test.

**Comment by smart-underworld** [comment]
I noticed this too. I had to explicitly restart the INDI service.

**Comment by bguthro** [comment]
I'll try to look into this soon, and make it a bit more reliable

**Comment by smart-underworld** [comment]
I think the common trait is that we both access RPi via external IP
addresses

**Comment by bguthro** [comment]
Fixed in main
