### ISSUE TITLE
python: can't open file 'seestar_alp/install': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Brnikat** [smart-underworld/seestar_alp#397]
To reproduce on a Ubuntu 24.04LTS system with Python 3.12.3 installed:
```

$ git clone https://github.com/smart-underworld/seestar_alp.git
$ cd seestar_alp
$ python install -r requirements.txt
```

Observe the error message given in the title.

FWIW, downloading seestar_alp-main.zip, unzipping it and changing directory to cd seestar_alp-main gives exactly the same result when an attempt is made to install.

**Comment by bguthro** [comment]
You should be using `pip3 install -r requirements.txt` - not python
