### ISSUE TITLE
How to close arm

### ISSUE THREAD

**Issue by Brnikat** [smart-underworld/seestar_alp#403]
I can't find any way to close the arm (opening is easy) without a total shutdown, which seems rather brutal and requires manual pressing of the power button.  (Just found that rebooting also shuts the arm.)

Is this intentional? If not, could a close-arm function be added please?

All looking rather fine otherwise!

**Comment by YungKC** [comment]
There's a command "park scope"

**Comment by Brnikat** [comment]
Ah.  Not an obvious place to look!

Offer: once I become familiar with the software, would you like me to write some documentation? I've been writing tech docs for several decades back when I was still employed.

**Comment by YungKC** [comment]
That would be fantastic. We are actively looking for more help to update
and improve the wiki pages.

**Comment by Brnikat** [comment]
Okey-doke.

Now having great fun exploring the app. It would be nice if it were a) dark and b) cloudless here so I can give it a thorough workout.
