### ISSUE TITLE
Mosaic Hangs if Plate Solve Fails

### ISSUE THREAD

**Issue by zeta2reticuli** [smart-underworld/seestar_alp#409]
If plate solving fails when moving to one of the tiles in a mosaic the procedure hangs. If you manually repeat the plate solve using the command windows and it is successful the procedure continues. Would it be possible to repeat a plate solve a few times if it initially fails to give the procedure an opportunity to continue?

**Comment by smart-underworld** [comment]
implemented and deployed.
