### ISSUE TITLE
add AAVSO variable star database query

### ISSUE THREAD

**Issue by erewhon** [smart-underworld/seestar_alp#419]
> Schedule -> Online DB search: Maybe please add AAVSO variable star database query ? The Seestar is ideal for the automatic imaging of variable stars. Some of the long known variable stars can also be found at SIMBAD. However, particularly current and interesting objects can only be found in the AAVSO database. Example: The current Nova V615 Vul. Query is IMHO simple, for this example 
> https://www.aavso.org/vsx/index.php?view=query.votable&ident=V615+VUL
> you get a XML structure with J2000 RA/DEC. 
> (The designations are not case sensitive) Would it please be possible to include this database in a future release ?

Suggested in Discord by DK3DUA.

**Comment by Brnikat** [comment]
Strongly recommend this enhancement. I would also make good use of it even though I have a work-around in that my VS work already includes a script which automates fetching AAVSO data. Unfortunately, it is in Perl not Python but I can provide if it helps writing Python access to VSP easier.

**Comment by xscode** [comment]
I can implement this quite easily.  A quick look through the api docs shows I can get a return in json which fits with the other searches with this format..
https://www.aavso.org/vsx/index.php?view=api.object&ident=V615+VUL&format=json

**Comment by Brnikat** [comment]
Thanks. That link shows me how to make my code simpler. Years ago it wasn't that easy!

**Comment by YungKC** [comment]
Fantastic. One nice-to-have is to allow for offline search as well by
reading a local data file from AAVSO as well, but the first priority is to
implement what you have proposed as an online option.

**Comment by xscode** [comment]
Merged with #421
