### ISSUE TITLE
Correction for INDI systemd service on Raspberry

### ISSUE THREAD

**Issue by RastaTaz** [smart-underworld/seestar_alp#423]
File `seestar_alp/raspberry_pi/systemd/INDI.service` should be corrected: in systemd logs for INDI service, we ca see following error:
`systemd[1]: /etc/systemd/system/INDI.service:14: Unknown key 'ExecPostStop' in section [Service], ignoring.`

Indeed, systemd doesn't know about `ExecPostStop` directive, it should instead be `ExecStop`.  
=> Once corrected, the error stops showing in the logs and `/tmp/seestar` fifo is deleted.

**Comment by bguthro** [comment]
Fixed in PR#425
