### ISSUE TITLE
Use Seestar_alp.exe as the ascom driver

### ISSUE THREAD

**Issue by spto** [smart-underworld/seestar_alp#453]
Hi Kai, I'm trying to use Seestar_alp.exe as the seestar ascom driver, because I have developed some other apps based on alpyca & ascom and I want to use it on seestar. 

Something I havn't been very clear about: 

1, is seestar_alp.exe dependant on config.toml? 
2. do users have to set the correct ip address of each seestar in config.toml? 
3. if so, how should the user check the correct ip address of each seestar? 
4. If I only wants to use Seestar_alp.exe as the ascom driver, do I still need to run app.py?

Could you please guide me through this? Thank you!

**Comment by bguthro** [comment]
1. You cannot connect via usb. This puts the seestar into target disk mode.
2. You cannot launch the SeeStar app first, and control via SSC/ALP. See the wiki link above for "Guest mode" details.

I'm going to close this ticket out, as this is not the proper way to get support. Please see the top level README.md file on how to join the discord server.
