### ISSUE TITLE
config.py failed to allow for per device override of parameters

### ISSUE THREAD

**Issue by smart-underworld** [smart-underworld/seestar_alp#488]
In the config.toml design, one can override the follwing settings per device:

[[seestars]]
name = "Seestar Alpha"
# ip_address should not have to be changed unless you have more than 1 seestar
ip_address = "seestar.local"
device_num = 1
# You can specify the following settings to override those found in the seestar_initialization section on a per-device level
#scope_aim_lat = 60          # start up latitude in degrees -90 to 80 (override default)
#scope_aim_lon = 20          # start up longitude in degrees 0 to 360 (override default)
#is_EQ_mode = false          # can be used to override default

With existing implementation of web based config.py, these overrides are deleted, and thus will need to be fixed.

**Comment by xscode** [comment]
Now Fixed
