### ISSUE TITLE
Extremely slow access / hang when accessing Raspberry from Mac / iOS device

### ISSUE THREAD

**Issue by skuske** [smart-underworld/seestar_alp#510]
If I access a Raspberry running Seestar ALP from a Mac mini or an iOS device, only **the very first** access via `http://[local IP address]:5432` is possible, further access is **not** possible, i.e. the Seestar service on the Raspberry no longer replies or only replies after about 10 to 20 seconds.

If I stop the Seestar service via `sudo systemctl stop seestar` and then restart it via `sudo systemctl start seestar` initial access to `http://[local IP address]:5432` is possible again. Afterwards, no further (or extremely slow) access is possible or no response is received and Safari or Chrome remain in an endless waiting loop for a response.

Is there a solution here or anything I can do to narrow down the cause? I have deactivated IPv6 as a test, without any improvement.

**Update:** for me it looks like the Seestar service gets stuck once an Apple device (MacOS or iOS) accesses the Seestar ALP interface. This happens with Safari or Chrome, tried both. I have disabled IPv6 on my Mac, but that does not help. Only restarting the service on the Raspberry helps, but then the problem starts all over again once one Mac / iOS device accesses the Seestar UI.

**Comment by bguthro** [comment]
@skuske - Could you please try again against the latest code? I believe we fixed a bug that exhibited these symptoms, but after a device was powered down, then back up. I'm hopeful it also addresses your situation.

**Comment by bguthro** [comment]
I can't repro these results. It would be helpful to see what call is hanging, from Chrome developer tools.
Also - collecting the logs from the support bundle zip (on the Support page) may help diagnose the issue. This sounds like a networking problem to me - possible IP conflict on your network...but I don't have any evidence to back that up.

**Comment by skuske** [comment]
@bguthro 

When I access it from a virtual Windows installation within Parallels on a Mac, there's no issue. It's just any MacOS or iOS device that cannot properly access the interface of the Seestar_ALP on a Raspberry.

I changed local IPs, disabled IPv6, but no change. I also checked the logs, but there's nothing unusual in there. And, the strange thing is that stopping and re-starting the seestar service fixes it once, but then the issue comes back as soon as I try to navigate in the Seestar ALP web interface.

I already spent days debugging this with changing network settings etc. - nothing helps.

**Comment by bguthro** [comment]
As far as I know, you're the only one reporting this...so there must be something in your environment that is different.
I can access from Chrome, Safari on OSX, and iOS without issues...as do others - so there is at least proof that it is not fundamentally broken.

What does the following show? 
```
arp <ssc ip address>
```

**Comment by skuske** [comment]
@bguthro 

There seems to be someone else with the same issue, if you show **all** (!) comments on my post here: https://www.facebook.com/groups/373417055173095/?multi_permalinks=581077471073718

Someone from France ...

**Comment by bguthro** [comment]
OK, so it isn't an IP conflict.
I'm not sure what it might be.

Try editing the `config.toml` file, and changing the IP address that the service binds to from `0.0.0.0` (all interfaces) - to a particular IP address (192.168.178.57)

**Comment by bguthro** [comment]
Another thing to try, is to provide a HAR capture from Chrome:
<img width="812" alt="image" src="https://github.com/user-attachments/assets/734043f3-d61b-4682-ac9d-fbccb1df3c29" />

Maybe there are clues in there.

If you can't get the support bundle, you can scp the alpyca.log* files off of the RPi from `~/seestar_alp/logs`

**Comment by skuske** [comment]
> OK, so it isn't an IP conflict. I'm not sure what it might be.
> 
> Try editing the `config.toml` file, and changing the IP address that the service binds to from `0.0.0.0` (all interfaces) - to a particular IP address (192.168.178.57)

Tried that, no change. 

Will check for the HAR capture from Chrome now ....

BTW: many thanks for your help so far! Much appreciated!

**Comment by skuske** [comment]
OK, it seems to be related to Safari, although I am sure that I saw the same issue in Chrome before, too. But now it looks like everything is fine when I use Chrome on MacOS but not Safari. Will do some more tests, even on my iOS devices ...

**Comment by skuske** [comment]
Well, it's not ~4s here, it something around 20s, sometimes it does not load at all. Anyway, in Chrome it is fine now, I think we can close this as it seems to be a problem of Safari ...

**Comment by bguthro** [comment]
Hmm... I may have been able to repro this in private browsing mode.
Not sure what to make of it yet. I'll do some digging when I get time.

**Comment by skuske** [comment]
OK, I was not using Private Mode ...

**Comment by skuske** [comment]
Tried that, no change. In Chrome it's still working fine.

**Comment by skuske** [comment]
Cool, thanks for your time. I also thought that it must have something to do with the network subsystem, as it kind of hinted at it from the beginning, especially after I checked all possible settings in my router and also disabled or deleted all potential causes (firewalls, private relay etc.).

I now use Chrome. That's fine so far. However, Chrome is also relatively slow on iOS, but I think that has to do with the fact that Apple doesn't really allow standalone browsers with their own architecture on iOS, as far as I know. They somehow still have to use the same APIs Safari uses.
