### ISSUE TITLE
Add twilight times on schedule pages

### ISSUE THREAD

**Issue by erewhon** [smart-underworld/seestar_alp#52]
We should calculate twilight times and show them to the user on the schedule pages to help them avoid starting the schedule too early or running too late.

This library could help: https://astroplan.readthedocs.io/en/stable/index.html

**Comment by movo-doo** [comment]
I am working on a python routine to show this information.  I am not well seasoned however I will be testing the code tomorrow again ... so far this is the output 
print (loc_sunrise)#2024-07-30 06:08:08-04:00
2024-07-30 06:08:08-04:00
>>> print (loc_sunset)#2024-07-30 20:42:51-04:00
2024-07-30 20:42:51-04:00
>>> print (loc_beg_civil)#2024-07-30 05:35:31-04:00
2024-07-30 05:35:31-04:00
>>> print (loc_end_civil)#2024-07-30 21:15:19-04:00
2024-07-30 21:15:19-04:00
>>> print (loc_beg_nautical)#2024-07-30 04:54:43-04:00
2024-07-30 04:54:43-04:00
>>> print (loc_end_nautical)#2024-07-30 21:55:55-04:00
2024-07-30 21:55:55-04:00
>>> print (loc_beg_astronomical)#2024-07-30 04:08:19-04:00
2024-07-30 04:08:19-04:00
>>> print (loc_end_astronomical)#2024-07-30 22:41:56-04:00
2024-07-30 22:41:56-04:00

once i am done with it i can post it up here and if someone wants to put it into the front end scheduling page then that would be great I would recommend highlighting the loc_geg_civil and loc_end_civil times as it is generally dark enough at those times to start imaging.

**Comment by erewhon** [comment]
That's fantastic!

**Comment by movo-doo** [comment]
This py snippet works on its own. sorry but i dont know if you can modify to use with SSC. Does have a few imports and a web call some of which may not be absolutely neccessary.

[python calc_twilights.txt](https://github.com/user-attachments/files/16451159/python.calc_twilights.txt)

I believe the 2 times that may be used the most and perhaps only need to be available on the scheduling screen is loc_beg_civil and loc_end_civil

**Comment by quake101** [comment]
Twilight times have been merged into main! Pull Request #96

**Comment by movo-doo** [comment]
Great work J …. Thanks a lot for your patience working with me and my rudimentary code. …Steve is looking forward to it as well… and hopefully many others.  You know people take for granted the features that people like you implement in these tools but I hope you know many of us appreciate yours and others work. 

On Aug 2, 2024, at 3:43 PM, Joe V ***@***.***> wrote:

﻿
Twilight times have been merged into main! Pull Request #96
