### ISSUE TITLE
Could not image below horizon

### ISSUE THREAD

**Issue by donpgolden** [smart-underworld/seestar_alp#522]
Using SeeStar ALP on Raspberry pi.  SeeStar firware version 3.68 and Alp version v2.3.5-8-g928026e.

When I try to do a mosaic image of Horsehead Nebula, It fails with the 'below horizon' message.  I thought this was fixed.

**Comment by xscode** [comment]
Do you have EQ mode selected in the settings and didn't do the startup sequence?

**Comment by donpgolden** [comment]
I have Eq Mode selected in Config.

I did the startup sequence manually so I could install my dew shield., i.e raise arm, install shield, autofocus, polar align and dark frames.   Then I added a 2 X 6 mosaic of IC 667 to the queue followed by an auto focus followed by a 3 X 4 mosaic of Running Man -   It all ran successfully until I hit funning man and that gave me the below horizon error.


Don Golden  <><
***@***.***
mobile 281 772 2991

**Comment by smart-underworld** [comment]
Wonder if the newest firmware change it's behavior. What version are you
using, and please include your log files for me to troubleshoot

**Comment by donpgolden** [comment]
SeeStar version 3.68

ALP.v2.3.5-8-g928026e on RPI
Don Golden  <><
***@***.***
mobile 281 772 2991

> On Dec 19, 2024, at 10:42 AM, smart-underworld ***@***.***> wrote:
> 
>  I have Eq Mode selected in Config.
> >
> > I did the startup sequence manually so I could install my dew shield., i.e
> > raise arm, install shield, autofocus, polar align and dark frames. Then I
> > added a 2 X 6 mosaic of IC 667 to the queue followed by an auto focus
> > followed by a 3 X 4 mosaic of Running Man - It all ran successfully until I
> > hit funning man and that gave me the below horizon error.
￼

**Comment by donpgolden** [comment]
Since I did the startup sequence manually, did the EQ mode not get sent to  the device?



SeeStar version 3.68

ALP.v2.3.5-8-g928026e on RPI
Don Golden  <><
***@***.***
mobile 281 772 2991

> On Dec 19, 2024, at 10:42 AM, smart-underworld ***@***.***> wrote:
> 
>  I have Eq Mode selected in Config.
> >
> > I did the startup sequence manually so I could install my dew shield., i.e
> > raise arm, install shield, autofocus, polar align and dark frames. Then I
> > added a 2 X 6 mosaic of IC 667 to the queue followed by an auto focus
> > followed by a 3 X 4 mosaic of Running Man - It all ran successfully until I
> > hit funning man and that gave me the below horizon error.
￼

**Comment by YungKC** [comment]
You should do the start up sequence explicitly first. It does a lot more than what you did manually.
