### ISSUE TITLE
clear schedule failed

### ISSUE THREAD

**Issue by donpgolden** [smart-underworld/seestar_alp#529]
after a failure to go to negative declination I cannot clear the schedule
[gensupportbundle (1).zip](https://github.com/user-attachments/files/18220417/gensupportbundle.1.zip)

**Comment by YungKC** [comment]
I looked at your log. It looks like you were trying to got to a target that's below horizon when your seestar is in a closed position, were the arm is still tucked pointing to the base of Seestar. This implies that you did not do the start-up sequence, and request it to raise the arm up., or you have parked Seestar.

Are in in EQ mode? Did you do the 3ppa (aka horizontal calibration)?

**Comment by YungKC** [comment]
This is most likely related to the other issue you filed, where you tried to goto a target And run a start up sequence. Alp is totally confused at this point.

**Comment by YungKC** [comment]
close for now.
