### ISSUE TITLE
Startup Seqence Skips Polar Alignment

### ISSUE THREAD

**Issue by donpgolden** [smart-underworld/seestar_alp#538]
Cleared Logs.  Fresh startup of SeeStar.   Ran Startup Sequence.  It seemed to skip polar alignment/
[gensupportbundle.zip](https://github.com/user-attachments/files/18268114/gensupportbundle.zip)

**Comment by YungKC** [comment]
From the log, it seems you have disabled auto horizontal calibration, which is needed for 3ppa. I have added code to override user preference if 3ppa is requested in start-up sequence.

**Comment by donpgolden** [comment]
Thanis.   I seem to recall at on point that disablement was required. 

Don Golden  <><
***@***.***
mobile 281 772 2991
