### ISSUE TITLE
Add default startup settings to seestar_alp API

### ISSUE THREAD

**Issue by erewhon** [smart-underworld/seestar_alp#54]
The user should be able to specify default startup settings, perhaps in the config.toml file.    There are settings the user might want to persist, including but not limited to:

- [ ] Dithering settings
- [ ] Persisting rejected frames

This functionality should ideally be independent of the GUI to accommodate different user workflows, but it should eventually be editable in the GUI.

**Comment by smart-underworld** [comment]
I suggest for startup settings, we invoke a startup command with all the
parameters we are interested in, kinda like the one I have but greatly
expanded. That way, both command line and GUI users will be on the same
page, and not dependent on Seestar's xml settings.

**Comment by erewhon** [comment]
This was added in the `seestar_initialization` section in `config.toml`.
