### ISSUE TITLE
Make improvements to the executable build scripts and process

### ISSUE THREAD

**Issue by erewhon** [smart-underworld/seestar_alp#59]
Recent changes to the application have broken the process that builds the self-contained executables.   

Once that is done, we should look at automating the process with GitHub actions if we can.

**Comment by erewhon** [comment]
@rrowley42 is working on this.

**Comment by rrowley42** [comment]
New builds of the zip were created and put in my google drive for now.  Created scripts to create the zips.

Will now work on integrating these into github actions

**Comment by rrowley42** [comment]
Github action was created to run PyInstaller for Windows and Linux, it won't work on MacOS because of code signing restrictions on Mac.
