### ISSUE TITLE
Possible to Change Sensor parameters for possible sensor upgrade?

### ISSUE THREAD

**Issue by crypticsymmetry** [smart-underworld/seestar_alp#6]
hi there, im new to this area, and was wondering if is it possible to change the sensor parameters to potentially allow sensor module upgrade? 
i saw a component called "aperturearea" and the value (1936.5) which closely corresponds with the height of the imx462 sensors 1937x1097. 
There is a imx415 (https://www.aliexpress.us/item/3256806715979473.html) which seems like a perfect sensor upgrade for fairly cheap, 4k, 8mp, good low light performance, low noise, same sensor size/format,  just different resolution/pixel size. and Still unsure if there custom sensor pcb is unique as it has connectors for the filters, and what type of ribbon cable is used for the image sensor module, but the linked imx415 sensor module looks fairly similar. 

Anyway just curious if this software would allow such modifications to the seestars config to allow a different sensor or would it require large code/hardware refactoring? 

Thanks for the time.

**Comment by mconsidine** [comment]
As far as I can see the code and the sensors are tightly integrated.  Even
with a different chip, the inherent field of view and resolution of the
optics won't change.

**Comment by smart-underworld** [comment]
Not within scope.
