### ISSUE TITLE
Support more flexible time input for images, mosaics

### ISSUE THREAD

**Issue by erewhon** [smart-underworld/seestar_alp#86]
Users should be able to enter minutes:seconds, or even hours:minutes:seconds instead of having to enter just seconds.

**Comment by movo-doo** [comment]
that would be great being able to have 3 controls like the ones on the settings page ..one for hours , one for minutes and one for seconds although do we really need a seconds one  all of them defaulting to 0 upon page opening and the last setting if adding another image to the schedule.

**Comment by smart-underworld** [comment]
completed
